name: Community
version: 0.0.1
author: [Janhektor, Aquaatic, Rincewind, WolfPlaysDE, TheRealJasmin, CreepPlays]
main: de.janhektor.community.Main
website: https://github.com/Janhektor/Community
description: Minecraft PvP Plugin - Janhektor's community project

